### PR TITLE
feat: release 0.5.0

### PR DESCRIPTION
**Pull request by CosminPerRam**
This PR aims to fix some issues related to the new CLI crate being added before releasing them.

When I tried to `cargo publish --dry-run` on the lib, I got the following error:
image
As `readme = "README.md"` is specified in the cargo file.

Seems like we need to have individual readmes for lib and cli (and also a 'base' readme to have here).

Some stuff that is not yet clear/decided to me:
* ~~I'm not sure if the node coverage badge would work when published, as the lib readme goes up a few levels to reach the svg (`../.././.github/badges/node.svg`).~~ edit: fixed by setting to to the raw path of the svg (raw.github.com).
* I don't think we should tie the cli and lib versions (before making this PR they both were on the same version, `0.4.1`) as its better to make individual changes and release them separately.

### CODE REVIEW

**Comment by cainthebest** [comment]
> I don't think we should tie the cli and lib versions

yeah i dont think its the best solution but as we release a copy of the repo source + cli bins, tags and semver would be a pain to manage

**Comment by CosminPerRam** [comment]
@cainthebest I would have thought on doing something like [actix-web](https://github.com/actix/actix-web/releases) does, any opinions on it?

**Comment by cainthebest** [comment]
> @cainthebest I would have thought on doing something like [actix-web](https://github.com/actix/actix-web/releases) does, any opinions on it?

After taking a look that LGTM

**Comment by cainthebest** [comment]
I think the only thing that we will need is new workflow for release as our current one would just append binarys to each release.

**Pull request merged**
