### PR TITLE
feat: add Ark: Survival Ascended support

### LINKED ISSUE #194: Add ASA (ARK Survival Ascended)
**What is this feature about?**
Looking forward for ASA being added to rust gamedig, it is already out in node-gamedig.

**Additional context/references**
It uses EOS servers, the data needed is probably in node-gamedig.

### PR DESCRIPTION
**Pull request by CosminPerRam**
Closes #194.

**WIP**, description to be filled with stuff eventually.

### CODE REVIEW

**Review by cainthebest — COMMENTED** [review]
This all LGTM but when testing in CLI I always get a bad request. I would assume it would be bad credentials but I would think to get a `401` or `403` not a `400`.

I have printed the request data from `request_with_form_data` for context
```
RUST_BACKTRACE=1 ./target/debug/gamedig-cli.exe query -g asa -i <IP> -p <Port + 1>
```

```log
Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.epicgames.dev")), port: Some(443), path: "/auth/v1/oauth/token", query: None, fragment: None }
Request(POST http://api.epicgames.dev:443/auth/v1/oauth/token, [Authorization: Basic eHl6YTc4OTFtdW9tUm15bklJSGFKQjlDT0JLa3dqNm46UFA1VUd4eXNFaWVOZlNyRWljYUQxTjJCYjNUZFh1RDd4SFljc2RVSFo3cw==, Content-Type: application/x-www-form-urlencoded])
[("grant_type", "client_credentials"), ("deployment_id", "ad9a8feffb3b4b2ca315546f038c3ae2")]
Error: Gamedig(GDError{ kind=PacketSend
  source=Status(400, Response[status: 400, status_text: Bad Request, url: http://api.epicgames.dev:443/auth/v1/oauth/token])
  backtrace=Backtrace [
      { fn: "std::backtrace_rs::backtrace::dbghelp::trace", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs", line: 131 },
      { fn: "std::backtrace_rs::backtrace::trace_unsynchronized", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\..\..\backtrace\src\backtrace\mod.rs", line: 66 },
      { fn: "std::backtrace::Backtrace::create", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\backtrace.rs", line: 331 },
      { fn: "std::backtrace::Backtrace::capture", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\backtrace.rs", line: 297 },
      { fn: "gamedig::errors::error::GDError::new", file: ".\crates\lib\src\errors\error.rs", line: 82 },     
      { fn: "gamedig::errors::error::GDError::from_error<enum2$<ureq::error::Error> >", file: ".\crates\lib\src\errors\error.rs", line: 92 },
      { fn: "gamedig::errors::kind::GDErrorKind::context<enum2$<ureq::error::Error> >", file: ".\crates\lib\src\errors\kind.rs", line: 51 },
      { fn: "gamedig::http::impl$2::request_with_form_data::closure$0<gamedig::protocols::epic::protocol::ClientTokenResponse>", file: ".\crates\lib\src\http.rs", line: 367 },
      { fn: "enum2$<core::result::Result<ureq::response::Response,enum2$<ureq::error::Error> > >::map_err<ureq::response::Response,enum2$<ureq::error::Error>,gamedig::errors::error::GDError,gamedig::http::impl$2::request_with_form_data::closure_env$0<gamedig::protocol", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\result.rs", line: 829 },
      { fn: "gamedig::http::HttpClient::request_with_form_data<gamedig::protocols::epic::protocol::ClientTokenResponse>", file: ".\crates\lib\src\http.rs", line: 365 },
      { fn: "gamedig::http::HttpClient::post_json_with_form<gamedig::protocols::epic::protocol::ClientTokenResponse>", file: ".\crates\lib\src\http.rs", line: 260 },
      { fn: "gamedig::protocols::epic::protocol::EpicProtocol::auth_by_client", file: ".\crates\lib\src\protocols\epic\protocol.rs", line: 86 },
      { fn: "gamedig::protocols::epic::protocol::EpicProtocol::query_raw", file: ".\crates\lib\src\protocols\epic\protocol.rs", line: 104 },
      { fn: "gamedig::protocols::epic::protocol::EpicProtocol::query", file: ".\crates\lib\src\protocols\epic\protocol.rs", line: 147 },
      { fn: "gamedig::protocols::epic::protocol::query_with_timeout", file: ".\crates\lib\src\protocols\epic\protocol.rs", line: 180 },
      { fn: "gamedig::games::query::query_with_timeout_and_extra_settings", file: ".\crates\lib\src\games\query.rs", line: 52 },
      { fn: "gamedig_cli::main", file: ".\crates\cli\src\main.rs", line: 445 },
      { fn: "core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<gamedig_cli::error::Error> > > (*)(),tuple$<> >", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\core\src\ops\function.rs", line: 250 },
      { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,enum2$<gamedig_cli::error::Error> > > (*)(),enum2$<core::result::Result<tuple$<>,enum2$<gamedig_cli::error::Error> > > >", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\sys_common\backtrace.rs", line: 154 },
      { fn: "std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,enum2$<gamedig_cli::error::Error> > > >", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\rt.rs", line: 167 },      
      { fn: "std::rt::lang_start_internal::closure$2", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\rt.rs", line: 148 },
      { fn: "std::panicking::try::do_call", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\panicking.rs", line: 552 },
      { fn: "std::panicking::try", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\panicking.rs", line: 516 },
      { fn: "std::panic::catch_unwind", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\panic.rs", line: 142 },
      { fn: "std::rt::lang_start_internal", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library\std\src\rt.rs", line: 148 },
      { fn: "std::rt::lang_start<enum2$<core::result::Result<tuple$<>,enum2$<gamedig_cli::error::Error> > > >", file: "/rustc/82e1608dfa6e0b5569232559e3d385fea5a93112\library\std\src\rt.rs", line: 166 },
      { fn: "main" },
      { fn: "invoke_main", file: "D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl", line: 78 },
      { fn: "__scrt_common_main_seh", file: "D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl", line: 288 },
      { fn: "BaseThreadInitThunk" },
      { fn: "RtlUserThreadStart" },
  ]
}
)
```

**Comment by cainthebest** [comment]
Ah, i see the issue its due to the tls feature. If epic only works with tls should we exclude it unless tls is enabled as otherwise its just a bad request?

**Comment by Douile** [comment]
I think we include it by default for the cli, maybe not for the lib. Although it is very easy to disable default features. I left it disabled originally because very few of the current games use http.

**Comment by Douile** [comment]
We should also probably feature gate creating EpicApis to tls only: because we use from_url instead of new we don't get the type system checking that Https exists and it just falls back to http.

**Comment by cainthebest** [comment]
> We should also probably feature gate creating EpicApis to tls only

this is what i was thinking.

Although im not too clued up on the http impl yet, I have only briefly looked

**Comment by cainthebest** [comment]
I was looking and possibly some form of http builder would help (Probs best for another pr), it would clean up some stuff and we can structure it where it helps us define it in a way that make it easy on our side.

eg

```rust
       let client = HttpClientBuilder::new()
            .protocol(HttpProtocol::Https)
            .base_url(EPIC_API_ENDPOINT)
            .timeout_settings(timeout_settings)
            .build()?;
```

client can then be passed up and defined with headers and path etc

**Comment by CosminPerRam** [comment]
image

Seems like we can't do cfg stuff on phf?

**Comment by Douile** [comment]
Proc macro thing I think. Looks like we can either add a build script that works around it or stop using phf for games and use something like HashMap (or any other map type that doesn't need codegen to be built).

**Comment by CosminPerRam** [comment]
I've decided to merge this without adding `asa` to the games definitions, as the problem of conditional entries for PHF should be decided in another discussion.

**Pull request merged**
