### PR TITLE
feat: FiveM

### PR DESCRIPTION
**Pull request by dollannn**

### CODE REVIEW

**Comment by dollannn** [comment]
I have no idea whether to separate info and players or to keep them together but this works for now.

**Comment by cainthebest** [comment]
Approving workflow to run checks

**Review by cainthebest — CHANGES_REQUESTED** [review]
This is starting to look good, ty for the pr.

There are some things that need doing before this can pass the CI.

- Format the code to fmt spec with the nightly formatter
- Add the example to the lib cargo with required features

Once this passes CI i will find the time for a full review, thanks again

**Comment by cainthebest** [comment]
What happened here? Pull bot?

**Comment by cainthebest** [comment]
@dollannn it looks like you have a bot running on your fork that is force pushing, this pr looks messed up from it.

**Comment by dollannn** [comment]
Sorry, will have a look at this sometime in the future, dont know when this becomes relevant for me again. I was struggling with rustfmt giving me very weird formatting suggestions so I just gave up 😅

**Pull request merged**
