### PR TITLE
Fix: try to match port on epic protocol

### PR DESCRIPTION
**Pull request by cainthebest**
This follows the same method as node to try and match ports on epic query's.

### CODE REVIEW

**Comment by cainthebest** [comment]
I have tested via running the query locally a few times and get the same results on the ip stated within issue.

**Comment by cainthebest** [comment]
This should be good for next patch also

**Comment by cainthebest** [comment]
This now lgtm and is working

**Review by CosminPerRam — APPROVED** [review]
Good stuff, the previous condition wasn't the same as Node's.

**Pull request merged**
