### PR TITLE
[Test] Add best effort test to validate game ID rules

### PR DESCRIPTION
**Pull request by Douile**
An attempt to implement the rules specified in #108 as a programmatic test.

### CODE REVIEW

**Comment by Douile** [comment]
The games that currently fail are either wrong (based on current rules as I understand):

- left 4 dead
- seven days to die
- quake 3: arena

Or ambiguous:

- minecraft legacy...
  - how the protocol version should be encoded into ID is not specified 

---

Further work (that I won't include in this PR):
- Validate the game definition matches the ID used for its module
  - This isn't needed if we generate them both from the same macro

**Comment by CosminPerRam** [comment]
Listed games are indeed wrongly identified.
Rule #6 is formed a bit strange, will reword it.
> how the protocol version should be encoded into ID is not specified

Well said, will also modify.
I will make a PR with these fixes and I will link it here.

**Comment by Douile** [comment]
I'm not sure on darkest hour there isn't a rule that specifies it should be how we currently have it but the ID we expect is not great.

**Comment by Douile** [comment]
Ah okay that makes sense. but it's going to be hard to implement I think. Yeah I don't blame you this is a bit spaghetti I should probably refactor.

**Comment by Douile** [comment]
After a further look at the messy code the reason this is ambiguous is because some games use - in-between words and we count them as different words (`Counter-Strike: Global Offensive`). Therefore the numbers at the end of Darkest Hour get split into two words.

I guess I could add a band-aid solution of if there are two numbers at the end of the word list combine them, this is a "best effort" after all. The nuance comes down to human interpretation and the code should be changed to match that.

**Comment by CosminPerRam** [comment]
CI passes, good to merge?

**Comment by Douile** [comment]
Assuming you are okay with these assumptions made about IDs:
- Numbers containing "-" are split numbers e.g. "10-40" == "1040"
  - Numbers with trailing "-" will panic e.g. "10-fourty"
- If the last word in a name is a number then it is the year
- Identifying roman numerals is hard: Only parse numerals if they are not the first word
- If expected ID doesn't match try again for the part after a "-" (for protocols)
- Parts in (brackets) are optional and ignored in most cases

Also should I remove the node-gamedig test?

**Comment by CosminPerRam** [comment]
Sounds good to me!

**Pull request merged**
